name: "oneshot"
description: "Zero/One shot prompting with Chat GPT from Open AI"
inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  model:
    description: "Model"
    required: false
    default: "gpt-3.5-turbo"
  temperature:
    description: "Temperature"
    required: false
    default: "0.7"
  prompt:
    description: "Prompt"
    required: true
outputs:
  output:
    description: "Output"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    MODEL: ${{ inputs.model }}
    TEMPERATURE: ${{ inputs.temperature }}
    PROMPT: ${{ inputs.prompt }}
